# -*- coding: utf-8 -*-
"""image_encryption_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2fAHV30L7s6GSCWRm_mhaeqNj9lf_jn
"""

import hashlib

def augment_password(password, symbols):
  augmented = ""
  for i in range(len(password)):
    augmented += password[i] + symbols[i%len(symbols)]
  return augmented

symbols = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "-", "=", "[",
           "]", "{", "}", "|", ";", ":", ",", ".", "<", ">", "?", "/", "`", "~"]

def hash_function(data):
  return hashlib.sha256(data.encode('utf-8')).digest()

def generate_large_key(password, target_length, bit_length = 3):

  large_byte_array = bytearray()
  password = augment_password(password, symbols)

  for i in range(0, len(password), bit_length):
    chunk = password[i:i+bit_length]
    chunk_hash = hash_function(chunk)
    large_byte_array.extend(chunk_hash)
    large_byte_array.extend(chunk_hash[::-1])


  while len(large_byte_array )< target_length:
    new_byte_array = bytearray()
    for i in range(0, len(large_byte_array), bit_length):
      segment = large_byte_array[i:i+bit_length]
      new_segment = segment.decode('latin-1', errors = 'ignore')
      new_segment_hash = hash_function(new_segment)
      new_byte_array.extend(new_segment_hash)

    large_byte_array.extend(new_byte_array)
    large_byte_array.reverse()


  large_key_string = large_byte_array.decode('utf-8', errors ='ignore')
  large_key_string = large_key_string[:target_length]
  return large_key_string

password = "secret_password"
target_length = 300000
large_key_string = generate_large_key(password, target_length)
print(len(large_key_string))

binary_string = ""

for i in large_key_string:
  b_i = format(ord(i), '08b')
  binary_string += b_i


segments_list = []

for i in range(0, len(binary_string), 8):
  segment = binary_string[i: i+8]
  segments_list.append(segment)
  reversed_segment = segment[::-1]
  segments_list.append(reversed_segment)
  mutated_segment = segment[4:8:1] + segment[0:4:1]
  segments_list.append(mutated_segment)

segments_list = segments_list[:786432]
print(len(segments_list))

dna_rules = {
        1: {'00': 'A', '01': 'G', '10': 'C', '11': 'T'},
        2: {'00': 'A', '01': 'C', '10': 'G', '11': 'T'},
        3: {'00': 'T', '01': 'G', '10': 'C', '11': 'A'},
        4: {'00': 'T', '01': 'C', '10': 'G', '11': 'A'},
        5: {'00': 'C', '01': 'T', '10': 'A', '11': 'G'},
        6: {'00': 'C', '01': 'A', '10': 'T', '11': 'G'},
        7: {'00': 'G', '01': 'T', '10': 'A', '11': 'C'},
        8: {'00': 'G', '01': 'A', '10': 'T', '11': 'C'}
    }

dna_rules_reversed = {
        1: {'A': '00', 'G': '01', 'C': '10', 'T': '11'},
        2: {'A': '00', 'C': '01', 'G': '10', 'T': '11'},
        3: {'T': '00', 'G': '01', 'C': '10', 'A': '11'},
        4: {'T': '00', 'C': '01', 'G': '10', 'A': '11'},
        5: {'C': '00', 'T': '01', 'A': '10', 'G': '11'},
        6: {'C': '00', 'A': '01', 'T': '10', 'G': '11'},
        7: {'G': '00', 'T': '01', 'A': '10', 'C': '11'},
        8: {'G': '00', 'A': '01', 'T': '10', 'C': '11'}
    }

dna_xor_table = {
            'A': {'A': 'A', 'T': 'T', 'C': 'C', 'G': 'G'},
            'T': {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'},
            'C': {'A': 'C', 'T': 'G', 'C': 'A', 'G': 'T'},
            'G': {'A': 'G', 'T': 'C', 'C': 'T', 'G': 'A'}
        }
def DNA_Encode(bits, rule):
    dna_sequence = []

    for i in range(0, len(bits), 2):
       bit_pair = bits[i:i+2]
       nucleotide = dna_rules[rule][bit_pair]
       dna_sequence.append(nucleotide)

    return "".join(dna_sequence)

def DNA_Decode(dna_sequence, rule):
    binary_data = []
    for nucleotide in dna_sequence:
      bit_pair = dna_rules_reversed[rule][nucleotide]
      binary_data.append(bit_pair)
    return "".join(binary_data)


def DNA_XOR(dna1, dna2):
  DNA_cipher = []
  for i in range(len(dna1)):
    dna_xor = dna_xor_table[dna1[i]][dna2[i]]
    DNA_cipher.append(dna_xor)

  return "".join(DNA_cipher)

from PIL import Image
import numpy as np

image_path = "/content/drive/MyDrive/4.2.07.tiff"
img = Image.open(image_path)

img_matrix = np.asarray(img)
# print(f"Image matrix shape: {img_matrix.shape}")
# print(img_matrix)
# display(img)

processed_img = img_matrix.copy()
height, width, channel = processed_img.shape
index = 0
for i in range(height):
  for j in range(width):
    for k in range(channel):
      if index < len(segments_list):
        rule = (index % 8) + 1
        key_segment = segments_list[index]
        original_value = processed_img[i, j, k]
        original_bin = format(original_value, '08b')

        key_dna = DNA_Encode(key_segment, rule)

        original_dna = DNA_Encode(original_bin, rule)

        xored_dna = DNA_XOR(key_dna, original_dna)

        decoded_bin = DNA_Decode(xored_dna, rule)

        cipher_value = int(decoded_bin, 2)

        processed_img[i, j, k] = cipher_value
        index += 1

processed_img = np.clip(processed_img, 0, 255).astype(np.uint8)

# print(processed_img)
# print("----------------------------------------------------------")
# print(img_matrix)
# type(processed_img)
print("Cipher Image: ")
cipher_img = Image.fromarray(processed_img)
display(cipher_img)

print("\n\n Original Image:")
display(img)

difference = np.sum(img_matrix != processed_img)
encryption_percentage = (difference /(height*width*channel)) * 100

print(f"\n\nPixels changed: {difference}/{height*width*channel} ({encryption_percentage:.2f}%)")

